version: '3.8'
services:

  xray-daemon:
    command: -o
    build: .
    environment:
      AWS_REGION: ap-east-1
      AWS_ACCESS_KEY_ID: ${XRAY_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${XRAY_AWS_SECRET_ACCESS_KEY}
    volumes:
      - "./log:/var/log"
    ports:
      - 2000:2000
      - 2000:2000/udp
