services:


  redis-node1:
    image: laed/redis
    build: ./redis
    ports:
      - "7000:7000"
      - "17000:17000"
    restart: always
    entrypoint: [redis-server, /etc/redis/rediscluster.conf, --port,"7000", --cluster-announce-ip,"${ip}"]

  redis-node2:
    image: laed/redis
    build: ./redis
    ports:
      - "7001:7001"
      - "17001:17001"
    restart: always
    entrypoint: [redis-server, /etc/redis/rediscluster.conf,--port,"7001",--cluster-announce-ip,"${ip}"]

  redis-node3:
    image: laed/redis
    build: ./redis
    ports:
      - "7002:7002"
      - "17002:17002"
    restart: always
    entrypoint: [redis-server, /etc/redis/rediscluster.conf,--port,"7002",--cluster-announce-ip,"${ip}"]

  redis-node4:
    image: laed/redis
    build: ./redis
    ports:
      - "7003:7003"
      - "17003:17003"
    restart: always
    entrypoint: [redis-server, /etc/redis/rediscluster.conf,--port,"7003",--cluster-announce-ip,"${ip}"]

  redis-node5:
    image: laed/redis
    build: ./redis
    ports:
      - "7004:7004"
      - "17004:17004"
    restart: always
    entrypoint: [redis-server, /etc/redis/rediscluster.conf,--port,"7004",--cluster-announce-ip,"${ip}"]

  redis-node6:
    image: laed/redis
    build: ./redis
    ports:
      - "7005:7005"
      - "17005:17005"
    restart: always
    entrypoint: [redis-server, /etc/redis/rediscluster.conf,--port,"7005",--cluster-announce-ip,"${ip}"]

  redis-cluster-creator:
    image: redis:6.0.3
    entrypoint: [/bin/sh,-c,'echo "yes" | redis-cli --cluster create ${ip}:7000 ${ip}:7001 ${ip}:7002 ${ip}:7003 ${ip}:7004 ${ip}:7005 --cluster-replicas 1']
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6

  redisinsight:
    image: "redis/redisinsight:2.50"
    container_name: redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight-data:/db
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6

  redisinsight-config:
    image: ellerbrock/alpine-bash-curl-ssl
    entrypoint: [ ]
    depends_on:
      - redisinsight
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6
    command: [
        "/bin/bash", "-c",
        "sleep 20 && curl --location 'redisinsight:5540/api/databases' \
          --request POST \
          --header 'Content-Type: application/json' \
          --data-raw  '{
              \"name\": \"127.0.0.1:7000\",
              \"host\": \"redis-node1\",
              \"port\": 7000,
              \"db\": 0,
              \"compressor\": \"NONE\",
              \"timeout\": 30000
          }'"
        ]


volumes:
  redisinsight-data:
    driver: local
